services:
  colmap:
    build:
      context: .
      dockerfile: Dockerfile.colmap
    image: vision_lab/colmap:cuda12.8-5090
    container_name: colmap_5090
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    volumes:
      # Map your local current directory to /workspace so you see files immediately
      - .:/workspace
    # This keeps the container running so you can log in interactively
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]